### ISSUE TITLE
how to build vectortileserver with Postgresql+Postgis DataBase in netcore api

### ISSUE THREAD

**Issue by PoreyTaken** [NetTopologySuite/NetTopologySuite.IO.VectorTiles#17]

**Comment by DGuidi** [comment]
you can try to extend the [provided sample](https://github.com/NetTopologySuite/NetTopologySuite.IO.VectorTiles/tree/develop/test/NetTopologySuite.IO.VectorTiles.Samples) adding the persistence layer to postgres/postgis
