### ISSUE TITLE
editor.config setting not observed in current code

### ISSUE THREAD

**Issue by rcollette** [NetTopologySuite/NetTopologySuite.IO.VectorTiles#19]
After pulling the project and reviewing with Rider, there are many cases where `var` is being used for built in types despite the fact that the editor config has
```
csharp_style_var_for_built_in_types = false:error
```

For instance, in MapBoxTileWriter.cs

![image](https://user-images.githubusercontent.com/136476/186038800-ae9cb29b-040e-41b5-b27e-eb0ff0b0b72b.png)

If the intent is to use var everywhere, then this setting should be changed to true

See:
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0007-ide0008

**Comment by FObermaier** [comment]
Before you start working on this: If I'm not mistaken this is addressed by @rbrundritt 's PR #16

**Comment by rbrundritt** [comment]
Yes, I went through and addressed most if not all of these warnings in PR #16

**Comment by FObermaier** [comment]
Closed with a5e99d5e12e160f6b1e0e2c0ce3ea71bc95be734
