### ISSUE TITLE
Encoding double value 0.0 in attribute table fails.

### ISSUE THREAD

**Issue by herrapa** [NetTopologySuite/NetTopologySuite.IO.VectorTiles#22]
Hi there!

I've encountered what I believe to be a bug in the encoder, otherwise I'm happy to be corrected on what I'm doing wrong.

The problem can be isolated with a small unit test:
(I've added this one in `RoundTripTests.cs`)

```c#
[Fact]
public void test_encode_property_double()
{
    AssertRoundTrip("POINT(0 0)", "{ \"type\": \"Point\", \"coordinates\": [0, 0] }",
        properties: ToAttributesTable(("test_double", 1.0), ("test_double_zero", 0.0)),
        expectedProperties: ToAttributesTable(("test_double", 1.0), ("test_double_zero", 0.0)));
}
```
Resulting in this:
```
Message: 
Assert.Equal() Failure
Expected: 0
Actual:   
```

If I change the value to a non zero value it seems to work:
```c#
[Fact]
public void test_encode_property_double()
{
    AssertRoundTrip("POINT(0 0)", "{ \"type\": \"Point\", \"coordinates\": [0, 0] }",
        properties: ToAttributesTable(("test_double", 1.0), ("test_double_zero", 0.1)),
        expectedProperties: ToAttributesTable(("test_double", 1.0), ("test_double_zero", 0.1)));
}
```

If the tiles are written to disc with a zero value attribute it causes them to not be readable by either QGIS or the python library `mapbox_vector_tile`.

**Comment by FObermaier** [comment]
Confirmed, same applies to default values of `float`, `int` and `long`.

**Comment by kolyanch** [comment]
Protobuf serializer skips default values for the most value types. 
One way to force writing default values is to implement methods for all properties in Tile class with ShouldSerialize naming pattern.

Currently ShouldSerialize is implemented only for bool property:
https://github.com/NetTopologySuite/NetTopologySuite.IO.VectorTiles/blob/83c856de17e447634b94ac9bb321b9040ce0bce3/src/NetTopologySuite.IO.VectorTiles.Mapbox/Tile.cs#L116

Just one line resolves issue for double values, tests completes successfully:
```C#
private bool ShouldSerializeDoubleValue() { return HasDoubleValue; }
```

**Comment by FObermaier** [comment]
Thanks @kolyanch for the hint. Much appreciated.
