### ISSUE TITLE
Release strategy

### ISSUE THREAD

**Issue by xivk** [NetTopologySuite/NetTopologySuite.IO.VectorTiles#8]
Do we want to release this package on nuget?

**Comment by FObermaier** [comment]
Yes, we want to do that, but let us address the `nullable` issues indicated by the build log first.

**Comment by xivk** [comment]
@FObermaier I see you added https://github.com/NetTopologySuite/NetTopologySuite.IO.VectorTiles/blob/develop/.editorconfig This feels very outdated, is this the codingstyle we expect in NTS in general? Especially avoiding the use of `var` feel very unnatural to me. If there is consensus about this I will off course yield to the majority.

**Comment by FObermaier** [comment]
@xivk `var` is used everywhere __except__ for builtin types. That is conformant with `NTS`.

**Comment by rbrundritt** [comment]
Do we have a minimum set of requirements we want to achieve before having a NuGet package released? We have a decent number of tests in this project. Some thoughts:

- Does NetTopologySuite have a plan to move from Newtonsoft.Json to System.Text.Json? If so, should we update this project first?
- There are a couple of features that might be nice to get in but may be fine to be added later. The two main ones I'm thinking of are #13 and #14. I thin #13 would be good to get in for the initial release, and #14 could be a possible future enhancement.
- If we want more samples before a NuGet release, I have a couple of samples I plan to make open source. I can pull in this library directly for now and make those samples available, then update to use the NuGet later.

**Comment by xivk** [comment]
I think the only thing blocking us is this: 

> Yes, we want to do that, but let us address the `nullable` issues indicated by the build log first.

But I honestly don't have the time right now to do this. If anyone is up for this and can do a pull request I can handle updating the build process to publish a package to nuget.

**Comment by rbrundritt** [comment]
I didn't notice that issue when I built it a few months ago. I'll take a look to see if I can figure it out (no promises).

**Comment by FObermaier** [comment]
I resolved that issue. If @xivk agrees, we can do a release.

**Comment by FObermaier** [comment]
A package was released
