### ISSUE TITLE
Use case for OverrideGetHashCodeAndEquals in Tile.Value

### ISSUE THREAD

**Issue by FObermaier** [NetTopologySuite/NetTopologySuite.IO.VectorTiles#9]
Nested `NetTopologySuite.IO.VectorTiles.Mapbox.Tile.Value` class has a static flag (`OverrideGetHashCodeAndEquals`) that controls whether `GetHashCode` and `Equals` return 
1. results based on content or 
2. just the results of their base implementations.

I'm wondering if there is a real use case for option [2]. If not, we should remove `OverrideGetHashCodeAndEquals` from the public API and return [1].

**Comment by rbrundritt** [comment]
I can't see a use for this method. It doesn't appear to be used anywhere within the libraries. Seems like a special case use. Would likely better to remove and the edge case scenario users could do this check/override in their code if needed.
